version: '3'
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  firefox:
    image: selenium/node-firefox-debug
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

